export createReducerFromObject from './createReducerFromObject'
export dispatchorRouterRedux from './dispatchorRouterRedux'
export createEventDispatcherMiddleWare from './dispatchorRouterRedux'
export connectDispatcherToStore from './connectDispatcherToStore'
export eventDispatcher from './eventDispatcher'
export default from './eventDispatcher'
